POST https://learn.codeit.kr/api/avatar-service/users
Content-Type: application/json

{
  "email": "jjay@land.com",
  "name": "jjay",
  "password": "jjay1234"
}

###
POST https://learn.codeit.kr/api/avatar-service/users
Content-Type: application/json

{
  "email": "fubao0720@land.com",
  "name": "복보",
  "password": "fubao0720"
}

### 
POST https://learn.codeit.kr/api/avatar-service/auth/login
Content-Type: application/json

{
  "email": "jjay@land.com",
  "password": "jjay1234"
}

###
POST https://learn.codeit.kr/api/avatar-service/auth/login
Content-Type: application/json

{
  "email": "fubao@everland.com",
  "password": "fubao0720"
}


###
GET https://learn.codeit.kr/api/link-service/users/me/links
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMDgiLCJpYXQiOjE3MDUzODY3MzMsImV4cCI6MTcwNTk5MTUzM30.lwWyfw3-bCmPxi_VlLkYJQ24iPCdrF7ZP92EKO89RBI


###
POST https://learn.codeit.kr/api/link-service/auth/login
Content-Type: application/json

{
  "email": "huibao@everland.com",
  "password": "huibao0707"
}

###
POST https://learn.codeit.kr/api/avatar-service/auth/token/refresh
Cookie: refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NSIsImlhdCI6MTcwNTc1NzQ5NCwiZXhwIjoxNzA2MzYyMjk0fQ.8yP1Dy_Bu9oOj3lHwwKw4lyoaJ-caC_5oluUsiLWJAE